[package]
name = "drg_mod_integration"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/trumank/drg-mod-integration"

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
clap = { version = "4.3.0", features = ["derive"] }
dialoguer = "0.10.4"
eframe = "0.22.0"
egui-dropdown = { git = "https://github.com/ItsEthra/egui-dropdown" }
egui_dnd = "0.4.0"
egui_extras = "0.22.0"
futures = "0.3.28"
hex = "0.4.3"
inventory = "0.3.6"
lazy_static = "1.4.0"
modio = { version = "0.7.1", features = ["rustls-tls"] }
regex = "1.8.3"
repak = { git = "https://github.com/trumank/repak.git", version = "0.1.3" }
reqwest = { version = "0.11.18", features = ["blocking"] }
reqwest-middleware = "0.2.2"
rfd = "0.11.4"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
sha2 = "0.10.6"
steamlocate = "2.0.0-alpha.0"
task-local-extensions = "0.1.4"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
typetag = "0.2.8"
uesave = { git = "https://github.com/trumank/uesave-rs.git", version = "0.2.0" }
unreal_asset = { git = "https://github.com/AstroTechies/unrealmodding.git", version = "0.1.12" }
url = "2.3.1"
zip = { version = "0.6.6", default-features = false, features = ["aes-crypto", "deflate", "time"] }

[patch.crates-io]
modio = { git = "https://github.com/trumank/modio-rs.git", branch = "dev" }

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.7"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.70.0"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc", "aarch64-apple-darwin"]
