[package]
name = "drg_mod_integration"
version = "0.2.9"
edition = "2021"
repository = "https://github.com/trumank/drg-mod-integration"

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
async-trait = "0.1.73"
clap = { version = "4.3.21", features = ["derive"] }
dialoguer = "0.10.4"
directories = "5.0.1"
eframe = "0.22.0"
egui_dnd = { git = "https://github.com/lucasmerlin/egui_dnd.git" }
futures = "0.3.28"
hex = "0.4.3"
image = { version = "0.24.7", default-features = false, features = ["png"] }
indexmap = { version = "2.0.0", features = ["serde"] }
inventory = "0.3.11"
lazy_static = "1.4.0"
modio = { git = "https://github.com/trumank/modio-rs.git", branch = "dev", features = ["rustls-tls"] }
obake = { version = "1.0.5", features = ["serde"] }
opener = "0.6.1"
regex = "1.9.3"
repak = { git = "https://github.com/trumank/repak.git", version = "0.1.3" }
reqwest = { version = "0.11.18", features = ["blocking"] }
reqwest-middleware = "0.2.3"
rfd = "0.11.4"
rust-ini = "0.19.0"
semver = "1.0.18"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
sha2 = "0.10.7"
steamlocate = "2.0.0-alpha.0"
task-local-extensions = "0.1.4"
thiserror = "1.0.44"
tokio = { version = "1.31.0", features = ["full"] }
tracing = { version = "0.1.37", features = ["attributes"] }
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "env-filter", "std", "registry"] }
typetag = "0.2.12"
unreal_asset = { git = "https://github.com/trumank/unrealmodding", branch = "patches" }
url = "2.4.0"
zip = { version = "0.6.6", default-features = false, features = ["aes-crypto", "deflate", "time"] }

[target.'cfg(target_env = "msvc")'.dependencies]
hook = { path = "hook", version = "0.1.0", artifact = "cdylib", target = "x86_64-pc-windows-msvc"}
[target.'cfg(not(target_env = "msvc"))'.dependencies]
hook = { path = "hook", version = "0.1.0", artifact = "cdylib", target = "x86_64-pc-windows-gnu"}

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"

[profile.release]
incremental = true
debug = 1

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.7"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.70.0"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
