[package]
name = "drg_mod_integration"
version = "0.2.10"
edition = "2021"
repository = "https://github.com/trumank/drg-mod-integration"

[dependencies]
ansi_term = "0.12.1"
anyhow = { version = "1.0.72", features = ["backtrace"] }
async-trait = "0.1.73"
clap = { version = "4.3.21", features = ["derive"] }
dialoguer = "0.10.4"
directories = "5.0.1"
eframe = "0.22.0"
egui_commonmark = "0.7.4"
egui_dnd = { git = "https://github.com/lucasmerlin/egui_dnd.git" }
futures = "0.3.28"
hex = "0.4.3"
image = { version = "0.24.7", default-features = false, features = ["png"] }
indexmap = { version = "2.0.0", features = ["serde"] }
inventory = "0.3.11"
lazy_static = "1.4.0"
modio = { git = "https://github.com/trumank/modio-rs.git", branch = "dev", default-features = false, features = ["rustls-tls"] }
obake = { version = "1.0.5", features = ["serde"] }
opener = "0.6.1"
path-slash = "0.2.1"
rayon = "1.7.0"
regex = "1.9.3"
reqwest = { version = "0.11.18", default-features = false, features = ["blocking", "rustls"] }
reqwest-middleware = "0.2.3"
rfd = "0.11.4"
rust-ini = "0.19.0"
self_update = { version = "0.37.0", features = ["archive-zip"] }
semver = "1.0.18"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
sha2 = "0.10.7"
steamlocate = "2.0.0-alpha.0"
task-local-extensions = "0.1.4"
tempfile = "3.7.1"
thiserror = "1.0.44"
tokio = { version = "1.31.0", features = ["full"] }
tracing = { version = "0.1.37", features = ["attributes"] }
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["fmt", "env-filter", "std", "registry"] }
typetag = "0.2.12"
uasset_utils = { git = "https://github.com/trumank/uasset_utils" }
unreal_asset = { git = "https://github.com/trumank/unrealmodding", branch = "patches" }
url = "2.4.0"
zip = { version = "0.6.6", default-features = false, features = ["aes-crypto", "deflate", "time"] }

[target.'cfg(windows)'.dependencies]
repak = { git = "https://github.com/trumank/repak", features = ["oodle"] }
[target.'cfg(not(windows))'.dependencies]
repak = { git = "https://github.com/trumank/repak" }
[target.'cfg(target_env = "msvc")'.dependencies]
hook = { path = "hook", version = "0.1.0", artifact = "cdylib", target = "x86_64-pc-windows-msvc"}
[target.'cfg(not(target_env = "msvc"))'.dependencies]
hook = { path = "hook", version = "0.1.0", artifact = "cdylib", target = "x86_64-pc-windows-gnu"}

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = false
strip = true

[profile.dev]
opt-level = 3
lto = "off"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.7"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.70.0"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
unix-archive = ".zip"
